import { Header } from '@/components/Header'
import './globals.css'
import { Nunito } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { ReactNode } from 'react'
config.autoAddCss = false
import 'react-loading-skeleton/dist/skeleton.css'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Github Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-base-background`}>
        <Header />
        <div className="mx-auto my-0 w-full max-w-screen-lg max-lg:max-w-screen-md max-md:max-w-screen-sm">
          {children}
        </div>
      </body>
    </html>
  )
}
